### ISSUE TITLE
Fluent Sample gives error after refresh browser and customization of controls 

### ISSUE THREAD

**Issue by satyajit-behera** [microsoft/fluentui-blazor#1010]
When I create the blazor fluent UI solution using the latest template, it works fine. But when I click the refresh button couple of times, it starts giving the error as mentioned below image:

![image](https://github.com/microsoft/fluentui-blazor/assets/10031739/afa33c9b-b4cc-4684-85fb-2990c4f8a006)

#Error: One or more errors occurred. (Root component type 'FluentSample.Components.Layout.NavMenu' could not be found in the assembly 'FluentSample'.)
    at Jn (marshal-to-js.ts:349:18)
    at Ul (marshal-to-js.ts:306:28)
    at dotnet.native.wasm:0x1faca
    at dotnet.native.wasm:0x1bf8b
    at dotnet.native.wasm:0xf172
    at dotnet.native.wasm:0x1e7e4
    at dotnet.native.wasm:0x1efda
    at dotnet.native.wasm:0xcfec
    at dotnet.native.wasm:0x440ad
    at e.<computed> (cwraps.ts:338:24)
## 

This gets resolved when I clear the cache in browser and appear again with refresh and any customizations to the component.

Same thing also appears when I do some customization and add <FluentSpacer /> inside <FluentHeader> .

nuget used: Microsoft.FluentUI.AspNetCore.Components 4.0.0 with .NET 8.

I am using windows 11 23H2, Visual Studio 2022 17.8.1.

**Comment by vnbaaij** [comment]
This is fixed in the next release. See #992.
