### ISSUE TITLE
V4.2.1 Error: Could not find 'GetGlobalLuminance' ('GetGlobalLuminance' was undefined). 

### ISSUE THREAD

**Issue by PrantoDas** [microsoft/fluentui-blazor#1196]
**Getting the following for Microsoft.FluentUI.AspNetCore.Components v4.2.1**
```
blazor.web.js:1 [2023-12-23T15:12:47.841Z] Error: Microsoft.JSInterop.JSException: Could not find 'GetGlobalLuminance' ('GetGlobalLuminance' was undefined).
Error: Could not find 'GetGlobalLuminance' ('GetGlobalLuminance' was undefined).
    at http://localhost:5041/_framework/blazor.web.js:1:734
    at Array.forEach (<anonymous>)
    at l.findFunction (http://localhost:5041/_framework/blazor.web.js:1:702)
    at b (http://localhost:5041/_framework/blazor.web.js:1:5445)
    at http://localhost:5041/_framework/blazor.web.js:1:3238
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (http://localhost:5041/_framework/blazor.web.js:1:3201)
    at fn._invokeClientMethod (http://localhost:5041/_framework/blazor.web.js:1:62541)
    at fn._processIncomingData (http://localhost:5041/_framework/blazor.web.js:1:60016)
    at connection.onreceive (http://localhost:5041/_framework/blazor.web.js:1:53657)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.FluentUI.AspNetCore.Components.FluentDesignTheme.OnAfterRenderAsync(Boolean firstRender) in /_/src/Core/Components/DesignSystemProvider/FluentDesignTheme.razor.cs:line 191
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```
![image](https://github.com/microsoft/fluentui-blazor/assets/24775726/d5365d68-e236-4f63-8f8c-8ffe0b1b0586)

**Comment by vnbaaij** [comment]
This is a cache problem on your side. Get the `FluentDesignTheme.razor.js` reloaded through the DevTools
