### ISSUE TITLE
fix: unhandled exception in FluentAnchor v4.4.0

### ISSUE THREAD

**Issue by thebarrettlo** [microsoft/fluentui-blazor#1468]
# 🐛 Bug Report

After upgrading to v4.4.0, it seems a rerendering of some component throws the following error in FluentAnchor. Possibly from https://github.com/microsoft/fluentui-blazor/commit/36f67c171eac1505c0f5484d2d2900c9118f1871--but on the [What's New page](https://www.fluentui-blazor.net/WhatsNew), that issue/change under 4.4.1, not 4.4.0.

## 💻 Repro or Code Sample

Upgrade to v4.4.0. FluentAnchor is not being used directly. Repro source not determined--possibly from within FluentToast?

## 🤔 Expected Behavior

No exception thrown.

## 😯 Current Behavior

```
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'mQviO1CHIcgoVMbg7mDuEcIafqRIwV9XyMjmIYfIqSY'.
      System.InvalidOperationException: Unable to set property 'onclick' on object of type 'Microsoft.FluentUI.AspNetCore.Components.FluentAnchor'. The error was: Unable to cast object of type 'Microsoft.AspNetCore.Components.EventCallback`1[Microsoft.AspNetCore.Components.Web.MouseEventArgs]' to type 'Microsoft.AspNetCore.Components.EventCallback'.
       ---> System.InvalidCastException: Unable to cast object of type 'Microsoft.AspNetCore.Components.EventCallback`1[Microsoft.AspNetCore.Components.Web.MouseEventArgs]' to type 'Microsoft.AspNetCore.Components.EventCallback'.
         at Microsoft.AspNetCore.Components.Reflection.PropertySetter.CallPropertySetter[TTarget,TValue](Action`2 setter, Object target, Object value)
         at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
         at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
         at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
```

* OS & Device: Windows 11 on PC
* Browser Microsoft Edge
* .NET 8.0
* Fluent UI Components 4.4.0

**Comment by vnbaaij** [comment]
We added the OnClick event callback in 4.4.0. We fixed the errors that caused in the demo in 4.4.1.

**Comment by thebarrettlo** [comment]
Is there a set release schedule for minor versions made available through NuGet?

**Comment by vnbaaij** [comment]
No, not yet. We are currently working on a method to release preview packages every couple of days
