### ISSUE TITLE
fix: FluentAnchor randomly throws unhandled exception at DisposeAsync

### ISSUE THREAD

**Issue by aliastopan** [microsoft/fluentui-blazor#1519]
# 🐛 Bug Report
I'm not sure is a bug. So far the application still running when the exception occurred. And [FluentAnchor](https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/Anchor/FluentAnchor.razor.cs) `DisposeAsync` stated:

> "The JSRuntime side may routinely be gone already if the reason we're disposing is that the client disconnected. This is not an error."

But the client is still connected and I often see this message being logged:
```
[18:24:59 WRN] Unhandled exception rendering component: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.     
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Microsoft.JSInterop.Implementation.JSObjectReference.DisposeAsync()
   at Microsoft.FluentUI.AspNetCore.Components.FluentAnchor.DisposeAsync() in /_/src/Core/Components/Anchor/FluentAnchor.razor.cs:line 151    
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<ProcessDisposalQueueInExistingBatch>g__GetHandledAsynchronousDisposalErrorsTask|79_0(Task result)
[18:24:59 ERR] Unhandled exception in circuit 'OIGlWiYi26kc9jxaj31LCVZB8TS5CWa82koh4JHLJkc'.
System.Threading.Tasks.TaskCanceledException: A task was canceled.     
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Microsoft.JSInterop.Implementation.JSObjectReference.DisposeAsync()
   at Microsoft.FluentUI.AspNetCore.Components.FluentAnchor.DisposeAsync() in /_/src/Core/Components/Anchor/FluentAnchor.razor.cs:line 151    
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<ProcessDisposalQueueInExistingBatch>g__GetHandledAsynchronousDisposalErrorsTask|79_0(Task result)
```

## 🤔 Expected Behavior
Handle exception more gracefully.

## 🌍 Your Environment

OS:
Windows 10 (19045.3930)
Ubuntu Server (22.04.3 LTS)

Browser:
Google Chrome Version 121.0.6167.161 (Official Build) (64-bit)

Nuget:
"Microsoft.FluentUI.AspNetCore.Components" Version="4.4.0"

**Comment by vnbaaij** [comment]
As it says in the code, this is not an error or a bug.
