### ISSUE TITLE
fix: Exception in FluentAnchor

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#1652]
# 🐛 Bug Report

## 💻 Repro or Code Sample

I left a Blazor page open for a while in the background. When I came back to it there was an error from FluentAnchor:

```
2024-03-07T17:49:39.8637041 warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: A task was canceled.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Microsoft.JSInterop.Implementation.JSObjectReference.DisposeAsync()
         at Microsoft.FluentUI.AspNetCore.Components.FluentAnchor.DisposeAsync() in /_/src/Core/Components/Anchor/FluentAnchor.razor.cs:line 151
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<ProcessDisposalQueueInExistingBatch>g__GetHandledAsynchronousDisposalErrorsTask|79_0(Task result)
```

## 🤔 Expected Behavior

No error.

## 😯 Current Behavior

Error.

## 💁 Possible Solution

Error comes from here:
https://github.com/microsoft/fluentui-blazor/blob/42378064ea2de885ba6ca63716b13c6a48b4ba03/src/Core/Components/Anchor/FluentAnchor.razor.cs#L145-L159

It appears to throw JSDisconnectedException or OperationCanceledException. Catch both?

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by JamesNK** [comment]
I also saw this with a list:

```
2024-03-07T20:33:43.5306944 warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: A task was canceled.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Microsoft.JSInterop.Implementation.JSObjectReference.DisposeAsync()
         at Microsoft.FluentUI.AspNetCore.Components.ListComponentBase`1.DisposeAsync() in /_/src/Core/Components/List/ListComponentBase.razor.cs:line 595
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<ProcessDisposalQueueInExistingBatch>g__GetHandledAsynchronousDisposalErrorsTask|79_0(Task result)
```

I suggest you add a utility method for disposing JSObjectReference and have it catch the two errors, then use that where ever you dispose.
