### ISSUE TITLE
fix: FluentSelect does not show the current value when 'Disabled'

### ISSUE THREAD

**Issue by StevenRasmussen** [microsoft/fluentui-blazor#1703]
# 🐛 Bug Report

When the `FluentSelect` is `Disabled` it does not show the currently selected value.

## 💻 Repro or Code Sample

Here is a repo that demonstrates the issue: [https://github.com/StevenRasmussen/FluentSelectIssue](https://github.com/StevenRasmussen/FluentSelectIssue)

## 🤔 Expected Behavior

`FluentSelect` should show the value regardless of when it is Disabled or not

## 😯 Current Behavior
Here is a video demonstrating the issue using the code in the repo above:

![FluentSelectIssue](https://github.com/microsoft/fluentui-blazor/assets/11198735/f4c9d146-84a3-48ae-9110-899c1f7e6516)

## 🌍 Your Environment

Fluent 4.5.0

**Comment by vnbaaij** [comment]
The cause of this lies in the underlying web components. Steping throught the Blazor source, I got the following ouptut at a certain point:
```
 at selectedIndexChanged (d:\Source\FluentUI\fluentui-blazor\src\Core\node_modules\@fluentui\web-components\dist\web-components.js:14518:10)
 at setValue (d:\Source\FluentUI\fluentui-blazor\src\Core\node_modules\@fluentui\web-components\dist\web-components.js:507:20)
 at set (d:\Source\FluentUI\fluentui-blazor\src\Core\node_modules\@fluentui\web-components\dist\web-components.js:669:26)
 at selectedIndexChanged (d:\Source\FluentUI\fluentui-blazor\src\Core\node_modules\@fluentui\web-components\dist\web-components.js:9343:12)
 at selectedIndexChanged (d:\Source\FluentUI\fluentui-blazor\src\Core\node_modules\@fluentui\web-components\dist\web-components.js:14517:11)
 at setValue (d:\Source\FluentUI\fluentui-blazor\src\Core\node_modules\@fluentui\web-components\dist\web-components.js:507:20)
 at set (d:\Source\FluentUI\fluentui-blazor\src\Core\node_modules\@fluentui\web-components\dist\web-components.js:669:26)
 at set value (d:\Source\FluentUI\fluentui-blazor\src\Core\node_modules\@fluentui\web-components\dist\web-components.js:14477:14)
 at updateValue (d:\Source\FluentUI\fluentui-blazor\src\Core\node_modules\@fluentui\web-components\dist\web-components.js:14498:12)
 at selectedIndexChanged (d:\Source\FluentUI\fluentui-blazor\src\Core\node_modules\@fluentui\web-components\dist\web-components.js:14518:10)
```

I'll add the label that it is blocked there.

**Comment by StevenRasmussen** [comment]
Is there anything I need to do to help get this resolved?  Or are you in contact with the team that produces the web components and are working with them to produce a fix?

**Comment by vnbaaij** [comment]
I've reached out on their Discord first. If needed I'll create an issue in the repo
