### ISSUE TITLE
fix: Collapse Splitter works but has an error when deploying to the web in FluentSplitter

### ISSUE THREAD

**Issue by Phucmh98** [microsoft/fluentui-blazor#1896]
# 🐛 Bug Report
 
**Collapse Splitter** of `FluentSplitter` works normally when I operate on **localhost** but when I deploy to the web I get an error.

How i can fix it?

## 💻 Repro or Code Sample
Here this error:
```
blazor.webassembly.js:1 Uncaught (in promise) Error: System.InvalidOperationException: There was an error parsing the event arguments. EventId: '118'.
 ---> System.NotSupportedException: DeserializeNoConstructor, JsonConstructorAttribute, Microsoft.FluentUI.AspNetCore.Components.SplitterCollapsedEventArgs Path: $ | LineNumber: 0 | BytePositionInLine: 1.
 ---> System.NotSupportedException: DeserializeNoConstructor, JsonConstructorAttribute, Microsoft.FluentUI.AspNetCore.Components.SplitterCollapsedEventArgs
   Exception_EndOfInnerExceptionStack
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& , Utf8JsonReader& , NotSupportedException )
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DeserializeNoConstructor(Type , Utf8JsonReader& , ReadStack& )
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Microsoft.FluentUI.AspNetCore.Components.SplitterCollapsedEventArgs, Microsoft.FluentUI.AspNetCore.Components, Version=4.6.1.24101, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , SplitterCollapsedEventArgs& )
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.FluentUI.AspNetCore.Components.SplitterCollapsedEventArgs, Microsoft.FluentUI.AspNetCore.Components, Version=4.6.1.24101, Culture=neutral, PublicKeyToken=null]].TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , SplitterCollapsedEventArgs& , Boolean& )
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.FluentUI.AspNetCore.Components.SplitterCollapsedEventArgs, Microsoft.FluentUI.AspNetCore.Components, Version=4.6.1.24101, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1[[Microsoft.FluentUI.AspNetCore.Components.SplitterCollapsedEventArgs, Microsoft.FluentUI.AspNetCore.Components, Version=4.6.1.24101, Culture=neutral, PublicKeyToken=null]].Deserialize(Utf8JsonReader& , ReadStack& )
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1[[Microsoft.FluentUI.AspNetCore.Components.SplitterCollapsedEventArgs, Microsoft.FluentUI.AspNetCore.Components, Version=4.6.1.24101, Culture=neutral, PublicKeyToken=null]].DeserializeAsObject(Utf8JsonReader& , ReadStack& )
   at System.Text.Json.JsonSerializer.ReadFromSpanAsObject(ReadOnlySpan`1 , JsonTypeInfo , Nullable`1 )
   at System.Text.Json.JsonSerializer.ReadFromSpanAsObject(ReadOnlySpan`1 , JsonTypeInfo )
   at System.Text.Json.JsonSerializer.Deserialize(String , Type , JsonSerializerOptions )
   at Microsoft.AspNetCore.Components.Web.WebEventData.ParseEventArgsJson(Renderer , JsonSerializerOptions , UInt64 , String , JsonElement )
   Exception_EndOfInnerExceptionStack
   at Microsoft.AspNetCore.Components.Web.WebEventData.ParseEventArgsJson(Renderer , JsonSerializerOptions , UInt64 , String , JsonElement )
   at Microsoft.AspNetCore.Components.Web.WebEventData.Parse(Renderer , JsonSerializerOptions , WebEventDescriptor , JsonElement )
   at Microsoft.AspNetCore.Components.Web.WebEventData.Parse(Renderer , JsonSerializerOptions , JsonElement , JsonElement )
   at Microsoft.AspNetCore.Components.RenderTree.WebRenderer.WebRendererInteropMethods.DispatchEventAsync(JsonElement eventDescriptor, JsonElement eventArgs)
   at System.Object.InvokeStub_WebRendererInteropMethods.DispatchEventAsync(Object , Span`1 )
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object , BindingFlags , Binder , Object[] , CultureInfo )
--- End of stack trace from previous location ---
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime , DotNetInvocationInfo& , IDotNetObjectReference , String )
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime , DotNetInvocationInfo , String )
    at b.endInvokeDotNetFromJS (https://ddg.corebim.com/_framework/blazor.webassembly.js:1:3136)
    at Object.bn [as endInvokeDotNetFromJS] (https://ddg.corebim.com/_framework/blazor.webassembly.js:1:59026)
    at https://ddg.corebim.com/_framework/dotnet.runtime.8.0.2.8j60y5zbay.js:3:177853
    at Ul (https://ddg.corebim.com/_framework/dotnet.runtime.8.0.2.8j60y5zbay.js:3:178687)
    at wasm://wasm/00a9b29a:wasm-function[216]:0x18d0c
    at wasm://wasm/00a9b29a:wasm-function[111]:0x151da
    at wasm://wasm/00a9b29a:wasm-function[104]:0x85fd
    at wasm://wasm/00a9b29a:wasm-function[138]:0x163ee
    at wasm://wasm/00a9b29a:wasm-function[2912]:0xc64dd
    at wasm://wasm/00a9b29a:wasm-function[2236]:0x9d177
```

## 🌍 Environment

* Device: Windows 11 
* Browser : Google Chrome
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.6.1]

**Comment by vnbaaij** [comment]
Hi,

You need to add this to your project file: 
```
<ItemGroup>
		<TrimmerRootAssembly Include="Microsoft.FluentUI.AspNetCore.Components" />
</ItemGroup>
```

**Comment by vnbaaij** [comment]
Solution provided. Closing this.

**Comment by Phucmh98** [comment]
Thank you for your support. I just deployed today and it's working
