### ISSUE TITLE
Communication Toast MissingMethodException after deployment to Static Web site

### ISSUE THREAD

**Issue by WINMAN174** [microsoft/fluentui-blazor#1898]
Locally on development box, Toast works fine. 

When deployed to static web site Toast throws an exception. 

blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Arg_NoDefCTor, Microsoft.FluentUI.AspNetCore.Components.CommunicationToast
System.MissingMethodException: Arg_NoDefCTor, Microsoft.FluentUI.AspNetCore.Components.CommunicationToast
   at System.RuntimeType.CreateInstanceMono(Boolean , Boolean )
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean , Boolean )
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Syncfusion.Blazor.SfComponentActivator.CreateInstance(Type componentType)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider , Type , IComponentRenderMode , Nullable`1 )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] , Int32 , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& , Int32 , Int32 , Int32 , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer , RenderBatchBuilder , Int32 , ArrayRange`1 , ArrayRange`1 )
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder , RenderFragment , Exception& )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

I'm using many other Fluent components. Not problems with any others. 

WebAssembly standalone app
Windows
Microsoft Edge
.NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by vnbaaij** [comment]
Hi,

You need to add this to your project file: 
```
<ItemGroup>
		<TrimmerRootAssembly Include="Microsoft.FluentUI.AspNetCore.Components" />
</ItemGroup>
```

**Comment by dvoituron** [comment]
I hadn't seen the reference to **Syncfusion**. Vincent is probably right.

**Comment by WINMAN174** [comment]
> Hi,
> 
> You need to add this to your project file:
> 
> ```
> <ItemGroup>
> 		<TrimmerRootAssembly Include="Microsoft.FluentUI.AspNetCore.Components" />
> </ItemGroup>
> ```

Far out! That worked. Had to look that one up. And yes I am using Syncfusion to supplement. Forgot to mention that. Conflict? 

Currently techno geeking out on the Bitcoin having event. 

Thanks guys! Nice work BTW.
