### ISSUE TITLE
fix: KeyCodeService in Microsoft.FluentUI.AspNetCore.Components.FluentDataGrid

### ISSUE THREAD

**Issue by StuFrankish** [microsoft/fluentui-blazor#1914]
# 🐛 Bug Report
Getting intermittent issues using the FluentDataGrid component.
The `Weather.razor` will initially load with data, displaying the component correctly, however, there will be a momentary flicker with the component reloads (shows "Loading...", then displays the component again with new data).

Navigating around using the Nav menu appears to be fine, but on a full page reload, the component never reloads again.
I only get an "Unhandled error" bar at the bottom of the screen with the following console trace:

```
blazor.web.js:1  crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot provide a value for property 'KeyCodeService' on type 'Microsoft.FluentUI.AspNetCore.Components.FluentDataGrid`1[[BlazorWebAppOidc.Client.Pages.Weather+WeatherForecast, BlazorWebAppOidc.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'. There is no registered service of type 'Microsoft.FluentUI.AspNetCore.Components.IKeyCodeService'.
System.InvalidOperationException: Cannot provide a value for property 'KeyCodeService' on type 'Microsoft.FluentUI.AspNetCore.Components.FluentDataGrid`1[[BlazorWebAppOidc.Client.Pages.Weather+WeatherForecast, BlazorWebAppOidc.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'. There is no registered service of type 'Microsoft.FluentUI.AspNetCore.Components.IKeyCodeService'.
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at **Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()**
```
## 💻 Repro or Code Sample
I've uploaded my repo [https://github.com/StuFrankish/FluentBlazorWithOIDC](https://github.com/StuFrankish/FluentBlazorWithOIDC)
It's largely based on the dotnet 8, blazor-samples, "BlazorWebAppOidc" project, with changes implementing FluentUI and some custom OIDC bits and pieces.

## 🤔 Expected Behavior

The component should load (as far as I can tell) once, and continue to load when navigating through the application and during a page refresh.

## 😯 Current Behavior

As described above, the component initially loads, then immediately reloads with an error.

https://github.com/microsoft/fluentui-blazor/assets/5624629/2cefb7fc-25db-4b2d-b91e-50a138b66900

## 🌍 Your Environment

Windows 11 Pro.
Microsoft Edge (latest update as at time of writing).
Visual Studio Professional 2022 (Preview 4 [17.10.0])

**Comment by StuFrankish** [comment]
> You probably need to ad the `builder.Services.AddFluentUIComponents()` in your client side project. The grid is expecting the service to be present.

That appears to have solved the issue. Thank you :)
