### ISSUE TITLE
Javascript error when loading Data Grid items with Virtualize Interactive server side rendering

### ISSUE THREAD

**Issue by danielpastoor** [microsoft/fluentui-blazor#1926]
# 🐛 Bug Report

blazor.web.js:1 
 Uncaught (in promise) Error: System.Text.Json.JsonException: The JSON value could not be converted to System.Single. Path: $ | LineNumber: 0 | BytePositionInLine: 4.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a number.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedNumber(JsonTokenType tokenType)
   at System.Text.Json.Utf8JsonReader.TryGetSingle(Single& value)
   at System.Text.Json.Utf8JsonReader.GetSingle()
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadAsObject(Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.ParseArguments(JSRuntime jsRuntime, String methodIdentifier, String arguments, Type[] parameterTypes)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson)

## 💻 Repro or Code Sample

<FluentDataGrid Items="@Items" Virtualize="true">
        <PropertyColumn Property="@(p => p.Status)" Sortable="true" />
        <PropertyColumn Property="@(p => p.DisplayName)" Sortable="true" />
    </FluentDataGrid>

## 🤔 Expected Behavior

That it won't give a javascript error

## 😯 Current Behavior

When I disable Virtualize it renders fine but if I enable it then it gives a Javascript error and won't render the grid items

## 🌍 Your Environment

* OS & Device: MacOs
* Browser Microsoft Edge
* .NET and Fluent UI Blazor library Version 8.0.4 and 4.7.1

**Comment by vnbaaij** [comment]
Please supply us with reproduction code in the form of a project or repository.

We do **not** have capacity to craft or compose a reproduction for every issue that gets raised. 

If no code or repository is provided, this issue will get closed automatically in **3** days

Help us to help you. Thanks
