### ISSUE TITLE
docs: fix custom timeout toast

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#2023]
# 🙋 Documentation Request

https://www.fluentui-blazor.net/Toast
Clicking on Custom Timeout throws an exception
![grafik](https://github.com/microsoft/fluentui-blazor/assets/32510006/21ed9fe0-6c54-4476-b65b-c66f858984d1)

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Arg_ArgumentOutOfRangeException Arg_ParamName_Name, period
System.ArgumentOutOfRangeException: Arg_ArgumentOutOfRangeException Arg_ParamName_Name, period
   at System.Threading.PeriodicTimer..ctor(TimeSpan )
   at Microsoft.FluentUI.AspNetCore.Components.CountdownTimer..ctor(Int32 timeout, CancellationToken cancellationToken)
   at Microsoft.FluentUI.AspNetCore.Components.FluentToast.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

Browser: Firefox v126 (64-Bit)

**Comment by dvoituron** [comment]
The problem comes from an invalid `TimeOut` value defined in the example. You must use `10_000` milliseconds.

```csharp
ToastService.ShowInfo("Info confirmation custom settings.", timeout: 10_000)
```

will be corrected via #2025
