### ISSUE TITLE
FluentProfileMenu does not work in Azure

### ISSUE THREAD

**Issue by franksandersen** [microsoft/fluentui-blazor#2037]
I am using FluentProfileMenu with visual studio, blazor wasm, .net 8 and the latest Microsoft.FluentUI.AspNetCore.Components, Version=4.7.2.24124 from nuget

Everything is working fine with visual studio on my dev machine. After deployment to Azure I get this error:

 **Unhandled exception rendering component: Could not resolve type with token 010000d9 from typeref (expected class 'Microsoft.FluentUI.AspNetCore.Components.FluentProfileMenu' in assembly 'Microsoft.FluentUI.AspNetCore.Components, Version=4.7.2.24124, Culture=neutral, PublicKeyToken=null')**
 
 
 My project file(s) already contains this (due to messagebox problems after deployed to Azure):
```
	<ItemGroup>
		<TrimmerRootAssembly Include="Microsoft.FluentUI.AspNetCore.Components" />
	</ItemGroup>

```
My profile menu code:
   ```
             <FluentProfileMenu 
                    StatusTitle="@_appData.User.Person?.FullName"
                    HeaderLabel="@_appData.User.Person?.Company?.Name"
                    FullName="@_appData.User.Person?.FullName"
                    EMail="@context?.User?.Identity?.Name"
                    ImageSize="40px"
                    FooterLink=""   
                    HeaderButton="Logg ut"
                    OnHeaderButtonClick="Logout"
                    Style="min-width: 330px;">
                </FluentProfileMenu> 
```

**Comment by vnbaaij** [comment]
Hi, we need minimal complete, working example code. We do **not** have capacity to construct reproduction code for every issue.
Help us to help you!

**Comment by franksandersen** [comment]
I understand, I will try to find time soon. In the meantime I post the complete error here: 
```

blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not resolve type with token 010000d9 from typeref (expected class 'Microsoft.FluentUI.AspNetCore.Components.FluentProfileMenu' in assembly 'Microsoft.FluentUI.AspNetCore.Components, Version=4.7.2.24124, Culture=neutral, PublicKeyToken=null')
System.TypeLoadException: Could not resolve type with token 010000d9 from typeref (expected class 'Microsoft.FluentUI.AspNetCore.Components.FluentProfileMenu' in assembly 'Microsoft.FluentUI.AspNetCore.Components, Version=4.7.2.24124, Culture=neutral, PublicKeyToken=null')
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 , RenderFragment )
   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder , RenderFragment , Exception& )
Dt @ blazor.webassembly.js:1
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not resolve type with token 010000d9 from typeref (expected class 'Microsoft.FluentUI.AspNetCore.Components.FluentProfileMenu' in assembly 'Microsoft.FluentUI.AspNetCore.Components, Version=4.7.2.24124, Culture=neutral, PublicKeyToken=null')
System.TypeLoadException: Could not resolve type with token 010000d9 from typeref (expected class 'Microsoft.FluentUI.AspNetCore.Components.FluentProfileMenu' in assembly 'Microsoft.FluentUI.AspNetCore.Components, Version=4.7.2.24124, Culture=neutral, PublicKeyToken=null')
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 , RenderFragment )
   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder , RenderFragment , Exception& )
Dt @ blazor.webassembly.js:1
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not resolve type with token 010000d9 from typeref (expected class 'Microsoft.FluentUI.AspNetCore.Components.FluentProfileMenu' in assembly 'Microsoft.FluentUI.AspNetCore.Components, Version=4.7.2.24124, Culture=neutral, PublicKeyToken=null')
System.TypeLoadException: Could not resolve type with token 010000d9 from typeref (expected class 'Microsoft.FluentUI.AspNetCore.Components.FluentProfileMenu' in assembly 'Microsoft.FluentUI.AspNetCore.Components, Version=4.7.2.24124, Culture=neutral, PublicKeyToken=null')
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 , RenderFragment )
   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder , RenderFragment , Exception& )
Dt @ blazor.webassembly.js:1

```

**Comment by vnbaaij** [comment]
Hej Frank, we have a rule where issues get closed if no feedback is received in three days. Please create a new issue once reproduction code is available, Thanks.

**Comment by franksandersen** [comment]
Thanks. I am lucky to say that this error went away after the latest .net 8.0.4 -> 8.0.5 packages upgrade. I tested this today.
