### ISSUE TITLE
fix: blazor.web.js breaks in version 4.8.0

### ISSUE THREAD

**Issue by VishwamKumar** [microsoft/fluentui-blazor#2213]
# 🐛 Bug Report

As I upgrade Microsoft.FluentUI.AspNetCore.Components 4.7.2 to 4.8.0, when application runs and loads in browser, I get the error on the bottom of the main page - An unhandled error has occurred. [Reload]

## 💻 Repro or Code Sample

Existing working code in 4.7.2 version [ App.razor]
<body>
    <Routes/>
    <div id="reconnect-modal" style="display: none;"></div>
    <script src="_framework/blazor.web.js" autostart="false"></script>
    <script src="boot.js"></script> 
</body>

## 🤔 Expected Behavior

It should not throw any errors.

## 😯 Current Behavior

blazor.web.js:1  [2024-06-18T18:25:36.720Z] Error: Microsoft.JSInterop.JSException: element.addEventListener is not a function
TypeError: element.addEventListener is not a function
    at Module.RegisterKeyCode (https://localhost:7252/_content/Microsoft.FluentUI.AspNetCore.Components/Components/KeyCode/FluentKeyCode.razor.js:47:17)
    at https://localhost:7252/_framework/blazor.web.js:1:3244
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:7252/_framework/blazor.web.js:1:3201)
    at gn._invokeClientMethod (https://localhost:7252/_framework/blazor.web.js:1:62841)
    at gn._processIncomingData (https://localhost:7252/_framework/blazor.web.js:1:60316)
    at connection.onreceive (https://localhost:7252/_framework/blazor.web.js:1:53957)
    at i.onmessage (https://localhost:7252/_framework/blazor.web.js:1:82102)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.FluentUI.AspNetCore.Components.FluentKeyCode.OnAfterRenderAsync(Boolean firstRender) in /_/src/Core/Components/KeyCode/FluentKeyCode.razor.cs:line 126
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
log @ blazor.web.js:1
blazor.web.js:1 [2024-06-18T18:25:36.721Z] Information: Connection disconnected.

## 🔦 Context

Unable to upgrade to 4.8.0, will have to wait for fix or solution.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

Browser: Microsoft Edge on Windows 11
.NET 8.0.4 and Blazor  Web App Project

**Comment by vnbaaij** [comment]
Duplicate. See #2205
