### ISSUE TITLE
fix: Hybrid Blazor Maui is not working

### ISSUE THREAD

**Issue by IdrisQashan** [microsoft/fluentui-blazor#2256]
My Server side was working just fine and I just made it into shared and also server side still working and after it I made it for maui and maui showed that issue

![image](https://github.com/microsoft/fluentui-blazor/assets/62256969/f8e9742d-1b92-43f9-be7b-e5467b443633)

```
Cannot read properties of undefined (reading 'readLocalStorage')
TypeError: Cannot read properties of undefined (reading 'readLocalStorage')
    at Module.addThemeChangeEvent (https://0.0.0.0/_content/Microsoft.FluentUI.AspNetCore.Components/Components/DesignSystemProvider/FluentDesignTheme.razor.js:16:44)
    at https://0.0.0.0/_framework/blazor.webview.js:1:3050
    at new Promise (<anonymous>)
    at g.beginInvokeJSFromDotNet (https://0.0.0.0/_framework/blazor.webview.js:1:3007)
    at https://0.0.0.0/_framework/blazor.webview.js:1:48020
    at EventTarget.<anonymous> (<anonymous>:7:62)
    at EmbeddedBrowserWebView.<anonymous> (<anonymous>:1:43721)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.FluentUI.AspNetCore.Components.FluentDesignTheme.OnAfterRenderAsync(Boolean firstRender) in /_/src/Core/Components/DesignSystemProvider/FluentDesignTheme.razor.cs:line 191
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

And this problem happen for FluentDesignTheme and I tried to make it in MainLayout.razor, Routes.razor
It didn't work and how to fix it.

**Comment by DavidH102** [comment]
This is the same issue as discussed by [#1130](https://github.com/microsoft/fluentui-blazor/discussions/1130)

**Comment by vnbaaij** [comment]
Indeed it is. Closing this as duplicate.
