### ISSUE TITLE
Fix: Error in FluentTabs: Could not find 'fluentOverflowInitialize'

### ISSUE THREAD

**Issue by miszelek** [microsoft/fluentui-blazor#2361]
# 🐛 Bug Report

After upgrading from 4.8.0 to 4.9.1 in my Blazor Server site I get this error on my page with FluentTabs:

Microsoft.JSInterop.JSException: Could not find 'fluentOverflowInitialize' ('fluentOverflowInitialize' was undefined).
Error: Could not find 'fluentOverflowInitialize' ('fluentOverflowInitialize' was undefined).
    at https://localhost:7148/_framework/blazor.server.js:1:734
    at Array.forEach (<anonymous>)
    at l.findFunction (https://localhost:7148/_framework/blazor.server.js:1:702)
    at _ (https://localhost:7148/_framework/blazor.server.js:1:5445)
    at https://localhost:7148/_framework/blazor.server.js:1:3238
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:7148/_framework/blazor.server.js:1:3201)
    at Xt._invokeClientMethod (https://localhost:7148/_framework/blazor.server.js:1:61001)
    at Xt._processIncomingData (https://localhost:7148/_framework/blazor.server.js:1:58476)
    at Xt.connection.onreceive (https://localhost:7148/_framework/blazor.server.js:1:52117)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at Microsoft.FluentUI.AspNetCore.Components.FluentTabs.OnAfterRenderAsync(Boolean firstRender) in /_/src/Core/Components/Tabs/FluentTabs.razor.cs:line 151
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

## 💁 Possible Solution

Might be related to issue 2338: Could not find 'fluentOverflowResized'

## 🌍 Your Environment

- OS & Device: Windows 11 on PC
- Browser: Google Chrome
- .NET 8.0.2 and FluentUI 4.9.1

**Comment by vnbaaij** [comment]
Try a hard refresh/clear cache. You're probably getting a cached script served

**Comment by miszelek** [comment]
Thanks for the quick response and fix!

Solved by Clear Cache in Chrome. Ticket can be closed.
