### ISSUE TITLE
Upgrade fom 4.8.1 to 4.9.1 throws Could not find 'fluentOverflowInitialize'

### ISSUE THREAD

**Issue by florianwachs** [microsoft/fluentui-blazor#2366]
Hi there, thanks for this aweome library!

I just now upgraded the components in my .NET 8 Blazor Server Project from 4.8.1 to 4.9.1.

When I start the solution, I get the following error output:

```
fluentOverflowInitializeError: Could not find 'fluentOverflowInitialize' ('fluentOverflowInitialize' was undefined).
    at https://localhost:7049/_framework/blazor.server.js:1:734
    at Array.forEach (<anonymous>)
    at l.findFunction (https://localhost:7049/_framework/blazor.server.js:1:702)
    at _ (https://localhost:7049/_framework/blazor.server.js:1:5445)
    at https://localhost:7049/_framework/blazor.server.js:1:3238
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:7049/_framework/blazor.server.js:1:3201)
    at Xt._invokeClientMethod (https://localhost:7049/_framework/blazor.server.js:1:61001)
    at Xt._processIncomingData (https://localhost:7049/_framework/blazor.server.js:1:58476)
    at Xt.connection.onreceive (https://localhost:7049/_framework/blazor.server.js:1:52117)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
         at Microsoft.FluentUI.AspNetCore.Components.FluentTabs.OnAfterRenderAsync(Boolean firstRender) in /_/src/Core/Components/Tabs/FluentTabs.razor.cs:line 151
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'QaSLcnfP7KQxFdbzY6OnpqkUGOq8AhhQWgvNFDRDNBE'.
      Microsoft.JSInterop.JSException: Could not find 'fluentOverflowInitialize' ('fluentOverflowInitialize' was undefined).
Error: Could not find 'fluentOverflowInitialize' ('fluentOverflowInitialize' was undefined).
    at https://localhost:7049/_framework/blazor.server.js:1:734
    at Array.forEach (<anonymous>)
    at l.findFunction (https://localhost:7049/_framework/blazor.server.js:1:702)
    at _ (https://localhost:7049/_framework/blazor.server.js:1:5445)
    at https://localhost:7049/_framework/blazor.server.js:1:3238
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:7049/_framework/blazor.server.js:1:3201)
    at Xt._invokeClientMethod (https://localhost:7049/_framework/blazor.server.js:1:61001)
    at Xt._processIncomingData (https://localhost:7049/_framework/blazor.server.js:1:58476)
    at Xt.connection.onreceive (https://localhost:7049/_framework/blazor.server.js:1:52117)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
         at Microsoft.FluentUI.AspNetCore.Components.FluentTabs.OnAfterRenderAsync(Boolean firstRender) in /_/src/Core/Components/Tabs/FluentTabs.razor.cs:line 151
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

```

**Comment by michelmoorlag** [comment]
Same problem here.
4.8.1 ->ok
4.9.0 ->Could not find 'fluentOverflowResized' (https://github.com/microsoft/fluentui-blazor/issues/2338)
4.9.1 ->Could not find 'fluentOverflowInitialize'

**Comment by vnbaaij** [comment]
It is using the older Javascript. Hard refresh or cache clear will resolve it

**Comment by michelmoorlag** [comment]
> It is using the older Javascript. Hard refresh or cache clear will resolve it

Yes, that seems to fix the issue. @vnbaaij Thank you

**Comment by chriss-barnard-bzy** [comment]
How would you suggest doing this if the application is running in production with users that you don't control?

**Comment by florianwachs** [comment]
> How would you suggest doing this if the application is running in production with users that you don't control? Somehow I need to force it to refresh the pulled in js files.
> 
> ![image](https://private-user-images.githubusercontent.com/93128041/349013681-da5cc24d-5f37-469f-9efc-3fa3308ac43e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzc0MzQsIm5iZiI6MTcyMTEzNzEzNCwicGF0aCI6Ii85MzEyODA0MS8zNDkwMTM2ODEtZGE1Y2MyNGQtNWYzNy00NjlmLTllZmMtM2ZhMzMwOGFjNDNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDEzMzg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMTBkN2Q5NjhjMWRkYThjOTM1OTQ4ODMxZjUwZmQxYzEzYjE5Y2U5ZDE1ZDc4M2E5MDA2MGY1NTBjMDZmNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zcyJYMPk34YfxpjSG6kazLwnJsATuIgtkJ8LTrPb1dU)

I'm facing the same issue with my production app, Is there a away to "cache bust" ? like adding a "?t=xyz" to the requesting file url. xyz could be the current version of the fluent ui components?

**Comment by chriss-barnard-bzy** [comment]
> > How would you suggest doing this if the application is running in production with users that you don't control? Somehow I need to force it to refresh the pulled in js files.
> > ![image](https://private-user-images.githubusercontent.com/93128041/349013681-da5cc24d-5f37-469f-9efc-3fa3308ac43e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzc0MzQsIm5iZiI6MTcyMTEzNzEzNCwicGF0aCI6Ii85MzEyODA0MS8zNDkwMTM2ODEtZGE1Y2MyNGQtNWYzNy00NjlmLTllZmMtM2ZhMzMwOGFjNDNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDEzMzg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMTBkN2Q5NjhjMWRkYThjOTM1OTQ4ODMxZjUwZmQxYzEzYjE5Y2U5ZDE1ZDc4M2E5MDA2MGY1NTBjMDZmNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zcyJYMPk34YfxpjSG6kazLwnJsATuIgtkJ8LTrPb1dU)
> 
> I'm facing the same issue with my production app, Is there a away to "cache bust" ? like adding a "?t=xyz" to the requesting file url. xyz could be the current version of the fluent ui components?

I've had a quick look in the code and I can see where the issue lies, I think it's a case of getting agreement to how this should be approached. My gut feeling suggests we should use the Assembly Version and amend the imports.

**Comment by dvoituron** [comment]
We are working a first Draft solution, using  `?v=<AssemblyVersion>`.
Comments are welcome.

See #2388
