### ISSUE TITLE
Critical error on new blank Project from Fluent-Template

### ISSUE THREAD

**Issue by deepx** [microsoft/fluentui-blazor#2476]
# 🐛 Bug Report

Hi. 
I created a new Fluent-Blazor-WebApp. The settings are: IndivitualAccounts, https, InteractiveRendermode: Auto and Interactivity location per page/component. It runs out of the box (after apply the default db-migration) but when i hit F5 after the project runs and shows the page in browser the Error (described below) shows up.

## 💻 Repro or Code Sample

Just a new FluentUI-Blazor-Webapp with the settings described above.

## 🤔 Expected Behavior

Just run wihout errors because its a new App.

## 😯 Current Behavior

The page displays: 
![image](https://github.com/user-attachments/assets/798e2885-ad28-4503-8b63-439cb7898e94)

When i take a closer look to the browserconsole it shows me the following:
`
blazor.web.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot provide a value for property 'LibraryConfiguration' on type 'Microsoft.FluentUI.AspNetCore.Components.FluentKeyCode'. There is no registered service of type 'Microsoft.FluentUI.AspNetCore.Components.LibraryConfiguration'.
System.InvalidOperationException: Cannot provide a value for property 'LibraryConfiguration' on type 'Microsoft.FluentUI.AspNetCore.Components.FluentKeyCode'. There is no registered service of type 'Microsoft.FluentUI.AspNetCore.Components.LibraryConfiguration'.
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
`

## 🌍 Your Environment

* OS: Windows 11, latest Visual Studio 17.10.5
* Browser Edge: Version 127.0.2651.74, Firefox: 128.0.3 and Chrome: Version 127.0.6533.88
* Fluent UI Blazor library Version 4.9.3
* Dotnet --info: 
`Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0`

If you need more informations, feel free to ask. 
regards
DeepX

**Comment by dvoituron** [comment]
Did you add this command to register all required services?
```csharp
builder.Services.AddFluentUIComponents();
```

See https://www.fluentui-blazor.net/CodeSetup

**Comment by deepx** [comment]
> Did you add this command to register all required services?
> 
> ```cs
> builder.Services.AddFluentUIComponents();
> ```
> 
> See https://www.fluentui-blazor.net/CodeSetup

Yes its in the Code, checked it twice, even when its directly from the Template.

**Comment by MarvinKlein1508** [comment]
I can reproduce the same issue with the steps above.

**Comment by MarvinKlein1508** [comment]
Yes, I tried it with latest template 4.9.3

**Comment by MarvinKlein1508** [comment]
@dvoituron https://github.com/MarvinKlein1508/FluentUI-Issue2476

SImply run the project. After a few seconds I get:
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot provide a value for property 'LibraryConfiguration' on type 'Microsoft.FluentUI.AspNetCore.Components.FluentKeyCode'. There is no registered service of type 'Microsoft.FluentUI.AspNetCore.Components.LibraryConfiguration'.
System.InvalidOperationException: Cannot provide a value for property 'LibraryConfiguration' on type 'Microsoft.FluentUI.AspNetCore.Components.FluentKeyCode'. There is no registered service of type 'Microsoft.FluentUI.AspNetCore.Components.LibraryConfiguration'.
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

**Comment by dvoituron** [comment]
Many thanks for your sample.

You can add this line `builder.Services.AddFluentUIComponents();` in the "second" `Program.cs` file (in `BlazorApp4.Client` project).
This code is probably needed when the project is loaded using the WebAssembly part of the `Auto` mode.
We will fix that in the next Release.

```csharp
var builder = WebAssemblyHostBuilder.CreateDefault(args);

builder.Services.AddAuthorizationCore();
builder.Services.AddCascadingAuthenticationState();
builder.Services.AddSingleton<AuthenticationStateProvider, PersistentAuthenticationStateProvider>();
builder.Services.AddFluentUIComponents();  // 👈

await builder.Build().RunAsync();
```

**Comment by deepx** [comment]
> Many thanks for your sample.
> 
> You can add this line `builder.Services.AddFluentUIComponents();` in the "second" `Program.cs` file (in `BlazorApp4.Client` project). This code is probably needed when the project is loaded using the WebAssembly part of the `Auto` mode. We will fix that in the next Release.
> 
> ```cs
> var builder = WebAssemblyHostBuilder.CreateDefault(args);
> 
> builder.Services.AddAuthorizationCore();
> builder.Services.AddCascadingAuthenticationState();
> builder.Services.AddSingleton<AuthenticationStateProvider, PersistentAuthenticationStateProvider>();
> builder.Services.AddFluentUIComponents();  // 👈
> 
> await builder.Build().RunAsync();
> ```

Looks like this fixed it. Thank you for your help on this. 
best regards
DeepX

**Comment by vnbaaij** [comment]
No, the missing `AddFluentUIComponents` in the Client project has been dealt with in the PR mentioned above

**Comment by MarvinKlein1508** [comment]
@paleocomburo have you run `dotnet new install Microsoft.FluentUI.AspNetCore.Templates` to update your templates?

**Comment by paleocomburo** [comment]
@MarvinKlein1508 I installed the templates for the very first time today. Never used them.
