### ISSUE TITLE
Recursive Focus Handling Causes 'Maximum Call Stack Size Exceeded' Error When Opening Nested Dialogs

### ISSUE THREAD

**Issue by Sweetli1415926** [microsoft/fluentui-blazor#2514]
# 🐛 Bug Report
When I design a button inside a FluentDialog to open another dialog, I encounter the following error:
Uncaught RangeError: Maximum call stack size exceeded.
    at i.focusFirstElement (web-components.js:11485:23)
    at HTMLDocument.handleDocumentFocus (web-components.js:11445:14)
    at i.focusFirstElement (web-components.js:11485:23)
    at HTMLDocument.handleDocumentFocus (web-components.js:11445:14)
    at i.focusFirstElement (web-components.js:11485:23)
    at HTMLDocument.handleDocumentFocus (web-components.js:11445:14)
    at i.focusFirstElement (web-components.js:11485:23)
    at HTMLDocument.handleDocumentFocus (web-components.js:11445:14)
    at i.focusFirstElement (web-components.js:11485:23)
    at HTMLDocument.handleDocumentFocus (web-components.js:11445:14) 
This occurs even though I have set the TrapFocus property to false on all dialog components.
## 💻 Repro or Code Sample

<FluentDialog @ref="detailDialog" TrapFocus="false" Modal="true" PreventScroll="false" @bind-Hidden="@Hidden" @ondialogdismiss=OnDetailDismiss>
    <FluentDialogHeader Visible="false" />
.....
  <FluentButton Color="white" BackgroundColor="red" OnClick="(()=>UnTakeInvoice())">Untake</FluentButton>
.....
</FluentDialog >
<FluentDialog @ref="detailDialog" TrapFocus="true" Modal="true" PreventScroll="false" @bind-Hidden="@Hidden" @ondialogdismiss=OnDetailDismiss>
    <FluentDialogHeader Visible="false" />
.....

await DialogService.ShowMessageBoxAsync(new DialogParameters<MessageBoxContent>()
            {
                Content = new()
                {
                    MarkupMessage = new MarkupString($"sample"),
                    Icon = new Icons.Regular.Size24.Warning(),
                    IconColor = Color.Error,
                },
                PrimaryAction = "confirm",
                SecondaryAction = "cancel",
                TrapFocus=false,
                Width = "350px",
            });

## 🌍 Your Environment

Blazor with Microsoft.FluentUI.AspNetCore.Components 4.9.3

**Comment by dvoituron** [comment]
Duplicated #948
See comment https://github.com/microsoft/fluentui-blazor/issues/948#issuecomment-1804000795
