### ISSUE TITLE
fix: In a wasm application, when installed on an iOS Fluent Tabs does not show overflow badge and throw an exception

### ISSUE THREAD

**Issue by ManbirSinghRakhra** [microsoft/fluentui-blazor#2571]
# 🐛 Bug Report

I have created a Blazor Web App, FluentTabs does not display overflow badge on the side on iOS. However, in a browser on desktop, this works well. Exception occurred on mobile shown as below. I am getting Not Supported Exception. Why?
Any help would be appreciated :)
`blazor.web.js:1  Uncaught (in promise) Error: System.NotSupportedException: DeserializeNoConstructor, JsonConstructorAttribute, Microsoft.FluentUI.AspNetCore.Components.OverflowItem Path: $[0] | LineNumber: 0 | BytePositionInLine: 2.
 ---> System.NotSupportedException: DeserializeNoConstructor, JsonConstructorAttribute, Microsoft.FluentUI.AspNetCore.Components.OverflowItem
   Exception_EndOfInnerExceptionStack
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(/reports/ReadStack& , Utf8JsonReader& , NotSupportedException )
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DeserializeNoConstructor(/reports/Type , Utf8JsonReader& , ReadStack& )
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Microsoft.FluentUI.AspNetCore.Components.OverflowItem, Microsoft.FluentUI.AspNetCore.Components, Version=4.9.3.24205, Culture=neutral, PublicKeyToken=null]].OnTryRead(/reports/Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , OverflowItem& )
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.FluentUI.AspNetCore.Components.OverflowItem, Microsoft.FluentUI.AspNetCore.Components, Version=4.9.3.24205, Culture=neutral, PublicKeyToken=null]].TryRead(/reports/Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , OverflowItem& , Boolean& )
   at System.Text.Json.Serialization.JsonCollectionConverter`2[[Microsoft.FluentUI.AspNetCore.Components.OverflowItem[], Microsoft.FluentUI.AspNetCore.Components, Version=4.9.3.24205, Culture=neutral, PublicKeyToken=null],[Microsoft.FluentUI.AspNetCore.Components.OverflowItem, Microsoft.FluentUI.AspNetCore.Components, Version=4.9.3.24205, Culture=neutral, PublicKeyToken=null]].OnTryRead(/reports/Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , OverflowItem[]& )
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.FluentUI.AspNetCore.Components.OverflowItem[], Microsoft.FluentUI.AspNetCore.Components, Version=4.9.3.24205, Culture=neutral, PublicKeyToken=null]].TryRead(/reports/Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , OverflowItem[]& , Boolean& )
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.FluentUI.AspNetCore.Components.OverflowItem[], Microsoft.FluentUI.AspNetCore.Components, Version=4.9.3.24205, Culture=neutral, PublicKeyToken=null]].ReadCore(/reports/Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1[[Microsoft.FluentUI.AspNetCore.Components.OverflowItem[], Microsoft.FluentUI.AspNetCore.Components, Version=4.9.3.24205, Culture=neutral, PublicKeyToken=null]].Deserialize(/reports/Utf8JsonReader& , ReadStack& )
   at System.Text.Json.JsonSerializer.ReadFromSpan[OverflowItem[]](/reports/ReadOnlySpan`1 , JsonTypeInfo`1 , Nullable`1 )
   at System.Text.Json.JsonSerializer.ReadFromSpan[OverflowItem[]](/reports/ReadOnlySpan`1 , JsonTypeInfo`1 )
   at System.Text.Json.JsonSerializer.Deserialize[OverflowItem[]](/reports/String , JsonSerializerOptions )
   at Microsoft.FluentUI.AspNetCore.Components.FluentTabs.OverflowRaisedAsync(/reports/String value)
    at y.endInvokeDotNetFromJS (blazor.web.js:1:3502)
    at Object.ri [as endInvokeDotNetFromJS] (blazor.web.js:1:165319)
    at dotnet.runtime.8.0.8.9z6kkxsnez.js:3:178428
    at Ll (dotnet.runtime.8.0.8.9z6kkxsnez.js:3:179262)
    at 00b21c96:0x1f99d
    at 00b21c96:0x1be41
    at 00b21c96:0xf00e
    at 00b21c96:0x1e693
    at 00b21c96:0x1ee89
    at 00b21c96:0xce5e`

* OS & Device: [Mobile OS]

**Comment by vnbaaij** [comment]
There is no reproduction code, no details on what version used, and complete disregard for the issue template we ask you to use. I am therefore closing this one. 

If you are ready to help us to help you, you can try opening an issue again.
