### ISSUE TITLE
FluentTextField - Object of type 'Microsoft.AspNetCore.Components.ChangeEventArgs' cannot be converted to type 'System.String'.

### ISSUE THREAD

**Issue by davidlloyduk** [microsoft/fluentui-blazor#2887]
# 🐛 Bug Report

Below code sample throws an exception:

`Object of type 'Microsoft.AspNetCore.Components.ChangeEventArgs' cannot be converted to type 'System.String'.`

```
Microsoft.AspNetCore.Components.Web.ErrorBoundary: Warning: Unhandled exception rendering component: Object of type 'Microsoft.AspNetCore.Components.ChangeEventArgs' cannot be converted to type 'System.String'.

System.ArgumentException: Object of type 'Microsoft.AspNetCore.Components.ChangeEventArgs' cannot be converted to type 'System.String'.
   at System.RuntimeType.CheckValue(Object& value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs, Boolean waitForQuiescence)
```

## 💻 Repro or Code Sample

```
<FluentTextField @bind-Value:event="oninput" @bind-Value="Value"></FluentTextField>
<FluentLabel>@Value</FluentLabel>

@code
{
    public string Value { get; set; } = string.Empty;
}
```

## 🤔 Expected Behavior

On key press in the `FluentTextField` it does not throw exception but binds correctly to `Value`

## 😯 Current Behavior

![Image](https://github.com/user-attachments/assets/a7606282-38ad-4248-be3e-2d26ff7b3751)

Type anything into the `FluentTextField` and this results:

![Image](https://github.com/user-attachments/assets/b0e6cf6e-2c8a-457b-b761-f32d37bc5019)

## 💁 Possible Solution

Swapping the `FluentTextField` to `input` will result in the correct behaviour

## 🔦 Context

Found whilst trying to get FluentTextField to update the binding on any key press/value and thus fire an internal validation method

## 🌍 Your Environment

Windows 11/Chrome (130.0.6723.71)
.net 8 + Blazor + FluentUI basic project + Visual Studio 2022 Pro
Microsoft.Fast.Components.FluentUI NuGet 3.0.*

**Comment by dvoituron** [comment]
If you want to update your `Value` variable immediately, as `OnInput` does, you can use the `Immediate` and `ImmediateDelay` attributes.
