### ISSUE TITLE
fix: FluentCalendar error in MAUI Blazor app

### ISSUE THREAD

**Issue by guillaume-brouillon** [microsoft/fluentui-blazor#476]
# 🐛 Bug Report

In Maui Blazor Hybrid, when selecting a date using FluentCalendar, the app crashes with error : 
Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day)
   at Microsoft.Fast.Components.FluentUI.FluentCalendar.OnDateSelected(CalendarSelectEventArgs args) in /_/src/Microsoft.Fast.Components.FluentUI/Components/Calendar/FluentCalendar.razor.cs:line 161
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

Everything is working fine with a pure blazor project. 

## 💻 Repro or Code Sample

Create a MAUI Blazor app. Configure it to use Fluent UI. Add a FluentCalendar. Select a date

## 🤔 Expected Behavior

Select the date

## 😯 Current Behavior

App crashes

## 🌍 Your Environment
Windows 11, Fluent UI Fast 2.3.6 Maui Blazor, OS Language : French

**Comment by vnbaaij** [comment]
I'm suspecting this has something to do with the French language. Which platform are you building the MAUI app for?

**Comment by guillaume-brouillon** [comment]
Thank you for your support.

Actually using [this workaround](https://github.com/microsoft/fluentui-blazor#tempory-workaround-for-maui-issues) solved the problem.

So I think we can close the issue.
