### ISSUE TITLE
fix: JSDisconnectedException in FluentOverflow

### ISSUE THREAD

**Issue by tlmii** [microsoft/fluentui-blazor#891]
# 🐛 Bug Report

Exception thrown when leaving a page that has a FluentOverflow:

```
Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Microsoft.JSInterop.Implementation.JSObjectReference.DisposeAsync()
         at Microsoft.Fast.Components.FluentUI.FluentOverflow.System.IAsyncDisposable.DisposeAsync() in /_/src/Core/Components/Overflow/FluentOverflow.razor.cs:line 143
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass85_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
         --- End of inner exception stack trace ---
```

## 💻 Repro or Code Sample

Internal repo we can share

## 🤔 Expected Behavior

No exception

## 😯 Current Behavior

Exception

## 💁 Possible Solution

This exception is handled in some components ([FluentAnchor](https://github.com/microsoft/fluentui-blazor/blob/b031690b8ece94c88e401e05558cf90729cb3e92/src/Core/Components/Anchor/FluentAnchor.razor.cs#L136C4-L150C6), for example) but not others 

## 🔦 Context

This doesn't show an error to the user, but it does show up in the logs

**Comment by aco-mreble** [comment]
@vnbaaij its the same for `FluentGrid` component:
```
Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at Microsoft.FluentUI.AspNetCore.Components.FluentGrid.DisposeAsync() in /_/src/Core/Components/Grid/FluentGrid.razor.cs:line 94
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass85_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
```
With version 4.4.1

**Comment by vnbaaij** [comment]
@aco-mreble please create a new issue (with repro steps!)
