### ISSUE TITLE
fix: Object not set to an reference of Object in FluentNavMenuItemBase

### ISSUE THREAD

**Issue by MatejMa2ur** [microsoft/fluentui-blazor#912]
After updating project to RC2 and packages to v 3.2.2 I am getting this error:

```
Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Fast.Components.FluentUI.FluentNavMenuItemBase.OnInitialized() in /_/src/Core/Components/NavMenuTree/FluentNavMenuItemBase.cs:line 132
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

# 🐛 Bug Report
```csharp
<FluentNavMenu Collapsible="false">
            <FluentNavMenuLink Text="Domov" Href="/" Icon="@(new Icons.Regular.Size20.Home())" />
            <FluentNavMenuGroup Href="/Template" Text="Testy" Icon="@(new Icons.Regular.Size20.DocumentOnePage())">
                <FluentNavMenuLink Text="Pridelenie Testov" Icon="@(new Icons.Filled.Size20.DocumentOnePage())" Disabled="true"/>
            </FluentNavMenuGroup>

            <FluentNavMenuGroup Text="Admin" Href="/Admin/Index" Icon="@(new Icons.Regular.Size20.FolderPeople())" Expanded="true">
                <FluentNavMenuLink Text="Otázky" Href="/questions" Icon="@(new Icons.Filled.Size20.Question())" />
                <FluentNavMenuLink Text="Kategórie" Href="/Topic" Icon="@(new Icons.Regular.Size28.Tag())" />
                <FluentNavMenuLink Text="Šablóny" Href="/Question-select" Icon="@(new Icons.Filled.Size20.Mail())" />
                <FluentNavMenuGroup Text="Používatelia" Href="/Users/Index" Icon="@(new Icons.Regular.Size20.FolderPeople())" Expanded="true">
                    <FluentNavMenuLink Text="Inšpektory" Href="/Admin" Icon="@(new Icons.Filled.Size20.Person())"/>
                    <FluentNavMenuLink Text="Zákazníci" Href="/User" Icon="@(new Icons.Filled.Size20.Group())"/>
                </FluentNavMenuGroup>
                <FluentNavMenuLink Text="Emailové šablóny" Href="/email-templates" Icon="@(new Icons.Filled.Size20.Mail())"/>
            </FluentNavMenuGroup>
        </FluentNavMenu>
```

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by vnbaaij** [comment]
Did you check the [Upgrade guide](https://www.fluentui-blazor.net/UpgradeGuide)?

**Comment by MatejMa2ur** [comment]
Thank you for your answer, I didn't know there was something like upgrade guide, thank you.
