### ISSUE TITLE
Issue in VS 2022 17.9 Preview 1 with Raz TagHelper Provider

### ISSUE THREAD

**Issue by grumpykiwi** [microsoft/fluentui-blazor#977]
# 🐛 Bug Report

After upgrading from the last RC to GA of .Net 8 and Fluent UI, I can no longer edit my razor pages. See attached error.
![FluentUI Issue](https://github.com/microsoft/fluentui-blazor/assets/43825887/ed3b6f53-fe29-4c30-b749-d323e1ee2900)

## 💻 Repro or Code Sample

I can provide the entire solution if needed - will need to strip out some bits which will require time. Cant post the zip here though.

## 🤔 Expected Behavior

I should be able to edit the razor pages without this error

## 😯 Current Behavior

I get the dreaded Razor TagHelper Provider Error and as the screenshot shows, makes it hard to edit the page when everything is now an error

## 💁 Possible Solution

I have tried repairing VS to no avail. Also created a brand new VM and installed latest VS bits, then opened the same project. Problem follows the project. Created a brand new clean Fluent UI server project in VS and it was fine. Something in the sln or csproj file me thinks.
## 🔦 Context

Cant reliably edit my blazor component pages anymore. 

## 🌍 Your Environment

Windows 11 Pro 23H2.
Visual Studio 2022 Preview 17.9.0 Preview 1.

**Comment by vnbaaij** [comment]
Have you tried deleting the .vs folder and the re-open the solution?

**Comment by dvoituron** [comment]
Weird. Have you tried cleaning up the solution folders: deleting all the 'bin` and `obj` folders and the `vs` folder?

**Comment by heroesch62** [comment]
I deleted the .vs folder and the re-opened the solution, but as soon as I enable in my .csprj file the line:

    **<PackageReference Include="Syncfusion.Blazor.Calendars" Version="23.2.4" />**
    
The error comes back:

**Feature 'Razor TagHelper Provider' is currently unavailable due to an internal error**. Show Stack trace:

StreamJsonRpc.RemoteInvocationException: Specified argument was out of the range of valid values.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__151`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__18`1.MoveNext()
RPC server exception:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
      at Microsoft.AspNetCore.Razor.Utilities.Checksum.Builder.<AppendStringValue>g__AppendData|14_0(SHA256 hash, Byte[] buffer, String value)
      at Microsoft.AspNetCore.Razor.Utilities.Checksum.Builder.AppendStringValue(String value)
      at Microsoft.AspNetCore.Razor.Language.DocumentationObject.AppendToChecksum(Builder& builder)
      at Microsoft.AspNetCore.Razor.Language.TagHelperDescriptor.BuildChecksum(Builder& builder)
      at Microsoft.AspNetCore.Razor.Language.TagHelperObject`1.ComputeChecksum()
      at Microsoft.AspNetCore.Razor.Language.TagHelperObject`1.GetHashCode()
      at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
      at System.Collections.Generic.HashSet`1.System.Collections.Generic.ICollection<T>.Add(T item)
      at Microsoft.AspNetCore.Razor.Language.TagHelperCollector`1.Collect(TagHelperDescriptorProviderContext context)
      at Microsoft.CodeAnalysis.Razor.ComponentTagHelperDescriptorProvider.Execute(TagHelperDescriptorProviderContext context)
      at Microsoft.AspNetCore.Razor.CompilationTagHelperResolver.<GetTagHelpersAsync>g__ExecuteProviders|2_1(ITagHelperDescriptorProvider[] providers, TagHelperDescriptorProviderContext context, ITelemetryReporter telemetryReporter)
      at Microsoft.AspNetCore.Razor.CompilationTagHelperResolver.GetTagHelpersAsync(Project workspaceProject, RazorProjectEngine projectEngine, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Razor.RemoteTagHelperProviderService.GetTagHelpersDeltaCoreAsync(Solution solution, ProjectSnapshotHandle projectHandle, String factoryTypeName, Int32 lastResultId, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspaceManager.RunServiceAsync[T](ServiceBrokerClient client, Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)

**Comment by vnbaaij** [comment]
Hi,

I'm sorry but I don't think we can help you with an error that pops up once you install a package not published by us...
